In [ ]:
import pandas as pd
import numpy as np
from collections import defaultdict

#### Описание данных

В папке Dat (https://github.com/hse-ds/iad-intro-ds/blob/master/2023/homeworks/Data.zip) находится информация о студентах. Всего 10 групп студентов. Файлы делятся на две категории:
    * Students_info_i - информация о студентах из группы i
    * Students_marks_i - оценки студентов из группы i за экзамены

In [ ]:
!wget https://github.com/hse-ds/iad-intro-ds/raw/master/2023/homeworks/Data.zip
!unzip /content/Data.zip

--2024-02-09 13:41:33--  https://github.com/hse-ds/iad-intro-ds/raw/master/2023/homeworks/Data.zip
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hse-ds/iad-intro-ds/master/2023/homeworks/Data.zip [following]
--2024-02-09 13:41:33--  https://raw.githubusercontent.com/hse-ds/iad-intro-ds/master/2023/homeworks/Data.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16727 (16K) [application/zip]
Saving to: ‘Data.zip.1’

Data.zip.1          100%[===================>]  16.33K  --.-KB/s    in 0s

2024-02-09 13:41:33 (108 MB/s) - ‘Data.zip.1’ saved [16727/16727]

Archive:  /content/Data.zip
replace Data/Students_info_0.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

### Одно из важных достоинств pandas $-$ это удобные методы реляционного взаимодействия с данными, аналогичные, например, возможностям SQL для слияния и конкатенации таблиц: merge, join, concat. Наличие готовых методов позволяет не реализовывать самостоятельно поэлементную обработку данных и оперировать сразу целыми таблицами данных.

Подробно об этих методах посмотрите тут: https://www.kaggle.com/residentmario/renaming-and-combining#Combining

#### Задание 1. Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата.¶

In [ ]:
inf = pd.read_csv('Data/Students_info_0.csv', sep = ',')
marks = pd.read_csv('Data/Students_marks_0.csv', sep = ',')
df = pd.merge(inf, marks, on = "index", how = "left")
for i in range(1, 10):
  inf = pd.read_csv(f'Data/Students_info_{i}.csv', sep = ',')
  marks = pd.read_csv(f'Data/Students_marks_{i}.csv', sep = ',')
  df_temp = pd.merge(inf, marks, on = "index", how = "left")
  df = pd.concat([df, df_temp])


df.sample(20)

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
74,74,male,group C,some high school,standard,none,group1,49,49,41
63,563,female,group D,some college,free/reduced,completed,group6,63,80,80
61,761,female,group D,some high school,standard,none,group8,48,58,54
1,1,female,group C,some college,standard,completed,group1,69,90,88
50,350,female,group B,bachelor's degree,standard,none,group4,52,65,69
41,241,female,group E,bachelor's degree,standard,none,group3,80,83,83
46,146,male,group B,some high school,standard,none,group2,88,84,75
51,551,male,group B,bachelor's degree,free/reduced,completed,group6,87,90,88
13,313,female,group C,associate's degree,free/reduced,completed,group4,68,67,69
69,369,female,group D,some high school,standard,none,group4,73,84,85
95,795,female,group E,associate's degree,free/reduced,completed,group8,57,68,73
52,52,male,group C,some college,standard,none,group1,53,44,42
64,364,male,group C,some college,standard,none,group4,59,60,58
19,519,female,group B,high school,free/reduced,completed,group6,67,78,79
23,623,male,group A,some college,standard,completed,group7,100,96,86
1,501,female,group B,associate's degree,standard,completed,group6,94,87,92
4,104,male,group C,some college,standard,completed,group2,98,86,90
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
15,815,male,group B,some high school,standard,completed,group9,94,86,87
13,413,male,group B,some high school,standard,completed,group5,63,67,67

#### Задание 2. Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

In [ ]:
df.drop("index", inplace=True, axis = 1)
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
5,female,group B,associate's degree,standard,none,group1,71,83,78
6,female,group B,some college,standard,completed,group1,88,95,92
7,male,group B,some college,free/reduced,none,group1,40,43,39
8,male,group D,high school,free/reduced,completed,group1,64,64,67
9,female,group B,high school,free/reduced,none,group1,38,60,50

#### Задание 3. Выведите на экран размеры полученной таблицы

In [ ]:
df.shape

(1000, 9)

#### Задание 4. Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [ ]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

#### Задание 5. Проверьте, есть ли в таблице пропущенные значения

In [ ]:
df.isnull().values.any()

False

#### Задание 6. Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing)

In [ ]:
df[['math score', 'reading score', 'writing score']].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

**Задание 7. Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.**

In [ ]:
df.groupby('test preparation course')[['math score', 'reading score', 'writing score']].mean()

                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

**Задание 8. Выведите на экран все различные значения из столбца lunch.**

In [ ]:
df.lunch.unique()

array(['standard', 'free/reduced'], dtype=object)

**Задание 9. Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas rename**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [ ]:
df = df.rename(columns={"parental level of education": "education", "test preparation course": "test preparation"})
df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...
95,female,group E,master's degree,standard,completed,group10,88,99,95
96,male,group C,high school,free/reduced,none,group10,62,55,55
97,female,group C,high school,free/reduced,completed,group10,59,71,65
98,female,group D,some college,standard,completed,group10,68,78,77
99,female,group D,some college,free/reduced,none,group10,77,86,86

**Зафиксируем минимальный балл для сдачи экзамена**

In [ ]:
passmark = 50

**Задание 10. Ответьте на вопросы:**
    * Какая доля студентов сдала экзамен по математике (passmark >= 50)?
    * Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
    * Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

In [ ]:
print((df['math score'] >= 50).mean(), " - доля студентов, сдавших матан") #доля студентов, сдавших матан


print(len(df[(df['test preparation'] == 'completed') & (df['math score'] >= 50)]) / (df['test preparation'] == 'completed').sum(), " - доля студентов, проходивших курс подготовки")

print(len(df[(df['gender'] == 'female') & (df['test preparation'] == 'none') & (df['math score'] < 50)]) / len(df[(df['gender'] == 'female') & (df['test preparation'] == 'none')]), " - женщины без подготовки, не сдавшие курс")

0.865  - доля студентов, сдавших матан
0.9217877094972067  - доля студентов, проходивших курс подготовки
0.20958083832335328  - женщины без подготовки, не сдавшие курс

**Задание 11. С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.**
    * Для каждой этнической группы выведите средний балл за экзамен по чтению
    * Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [ ]:
df.groupby('race/ethnicity')[['reading score']].mean() #средний балл по чтению
%timeit df.groupby('race/ethnicity')[['reading score']].mean()

1.49 ms ± 212 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [ ]:
df.groupby('education')[['writing score']].min() #минимальный балл за экз по письму
%timeit df.groupby('education')[['writing score']].min()

2.4 ms ± 548 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

**Задание 12. Выполните задание 11 с помощью циклов. Сравните время выполнения.**

In [ ]:
%%timeit
d = defaultdict(list)
for r in df.itertuples():
  d[r._2].append(r._8)

for k, v in d.items():
  d[k] = sum(v) / len(v)

res

#Выполняется дольше чем в 11 номере

3.6 ms ± 1.13 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

**Задание 13. Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выыведите средний балл по каждому из предметов.**

Это можно сделать с помощью сводных таблиц (pivot_table):

https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas

In [ ]:
pd.pivot_table(df, index=['gender', 'education'], aggfunc='mean')

<ipython-input-91-85b5c9cab5e3>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  pd.pivot_table(df, index=['gender', 'education'], aggfunc='mean')

                           math score  reading score  writing score
gender education
female associate's degree   65.916264      74.714976      74.716586
       bachelor's degree    68.410615      77.692737      78.779330
       high school          59.676471      68.384191      66.919118
       master's degree      66.827225      77.486911      78.403141
       some college         65.183515      73.272162      73.814930
       some high school     59.932136      69.698603      68.950100
male   associate's degree   72.274510      68.525847      66.600713
       bachelor's degree    70.244444      67.793651      67.177778
       high school          64.706406      61.158363      58.195730
       master's degree      76.023438      74.312500      73.671875
       some college         70.013722      65.761578      63.816467
       some high school     69.046653      65.858012      62.557809

#### Задание 14. Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [ ]:
df['Math_PassStatus'] = np.where(df['math score']>= 50, 'P', 'F')
df['Writing_PassStatus'] = np.where(df['writing score']>= 50, 'P', 'F')
df['Reading_PassStatus'] = np.where(df['reading score']>= 50, 'P', 'F')
df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Writing_PassStatus,Reading_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,F,P
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...
95,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P
96,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P
97,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P
98,female,group D,some college,standard,completed,group10,68,78,77,P,P,P
99,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P

#### Задание 15. Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [ ]:
df["OverAll_PassStatus"] = np.where((df['Math_PassStatus'] == 'P') & (df['Writing_PassStatus'] == 'P') & (df['Reading_PassStatus'] == 'P'), 'P', 'F')

print(len(df[df['OverAll_PassStatus'] == 'P']), " - количество студентов, сдавших все экзы")

812  - количество студентов, сдавших все экзы

#### Задание 16. Переведем баллы в оценки

### Система перевода баллов в оценки
####    больше 90 = A
####      80-90 = B
####      70-80 = C
####      60-70 = D
####      50-60 = E
####    меньше 50 = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

**В случае, если средний балл попадает на границу между оценками (т.е. равен ровно 60, 70 или 80 баллов), вы можете интерпретировать условие на своё усмотрение (т.е. можете поставить за 60 баллов оценку D, а можете - E).**

In [ ]:
dic = {0: 'F',50: 'E', 60: 'D', 70: 'C', 80: 'B',90: 'A'}

def GetGrade(average_mark):
    for i in dic:
      if average_mark <= i:
        return dic[i]


df["Grade"] = (df.iloc[:, 6:9].mean(axis=1)).apply(GetGrade)


df['Grade'].value_counts()

C    260
B    253
D    184
A    144
E    109
Name: Grade, dtype: int64